# Generated by Django 4.0.5 on 2022-06-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_author', models.CharField(max_length=12)),
                ('article_name', models.CharField(max_length=60)),
                ('article_body', models.TextField()),
                ('article_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
