# Generated by Django 4.0.5 on 2022-06-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=models.CharField(choices=[('python / django', 'python / django'), ('php', 'php'), ('java', 'java'), ('ruby', 'ruby'), ('js / js frameworks', 'js / js frameworks'), ('linux / server operation', 'linux / server operation'), ('databases', 'databases'), ('metapost', 'metapost'), ('tips and tricks', 'tips and tricks'), ('workflow', 'workflow'), ('etc', 'etc')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
